language: go

matrix:
  include:
    - go: 1.x
    - go: 1.11.x
      env: GO111MODULE=off
    - go: 1.11.x
      env: GO111MODULE=on
    - go: 1.12.x
      env: GO111MODULE=off
    - go: 1.12.x
      env: GO111MODULE=on
    - go: master
  script:
    - go test -v ./...
